FROM oven/bun:1
ARG DATABASE_URL
WORKDIR /usr/src/app

ENV DATABASE_URL=$DATABASE_URL
COPY drizzle.config.ts ./
COPY src/lib/server ./src/lib/server
RUN bun install drizzle-kit drizzle-orm postgres

CMD "bun x drizzle-kit generate && bun x drizzle-kit migrate"